Console.Write ("1");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("2");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("3");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("4");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("5");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("6");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("7");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("8");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("9");
Console.Write (" ");
Thread.Sleep (1000);
Console.Write ("10");